# Generated by Django 2.0.4 on 2018-05-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bmiinfo_bmi_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmiinfo',
            name='bmi_stat',
        ),
    ]
